- name: Wait for systems to boot up and cloud-init to complete
  hosts: all
  gather_facts: no
  any_errors_fatal: true
  tasks:
    - name: Wait up to 300 seconds
      wait_for_connection:
        delay: 3
        sleep: 5
        timeout: 300

    - name: Gather all facts of cloud init
      cloud_init_data_facts:
      register: result

    - name: Wait for cloud init to finish
      cloud_init_data_facts:
        filter: status
      register: res
      until: "res.cloud_init_data_facts.status.v1.stage is defined and not res.cloud_init_data_facts.status.v1.stage"
      retries: 50
      delay: 5

- name: Configure hosts
  hosts: all
  gather_facts: true
  any_errors_fatal: true
  roles:
    - ansible_role_create_hosts_file

- name: Configure broker data disks
  hosts: kafka_broker
  gather_facts: true
  gather_subset:
    - "distribution"
    - "distribution_release"
    - "distribution_major_version"
    - "distribution_version"
    - "os_family"
  any_errors_fatal: true
  vars:
    #broker_log_dirs: /var/lib/kafka
    #broker_log_dirs_prefix: data
    #broker_log_filesystem: xfs
  roles:
    - ansible_role_mount_broker_disks

- name: Include a play after another play
  vars:
    installation_method: archive
    redhat_java_package_name: java-11-openjdk
    confluent_archive_file_source: https://192.168.240.11/files/cp/7.6/confluent-7.6.1.tar.gz
    confluent_package_version: 7.6.1
    kafka_broker_custom_listeners:
      broker:
        name: BROKER
        port: 9091
        ssl_enabled: false
        ssl_mutual_auth_enabled: false
        sasl_protocol: none
      internal:
        name: INTERNAL
        port: 9092
        ssl_enabled: false
        ssl_mutual_auth_enabled: false
        sasl_protocol: none
      client_listener:
        name: CLIENT
        port: 9093
        ssl_enabled: true
        ssl_mutual_auth_enabled: true
        sasl_protocol: scram
  ansible.builtin.import_playbook: confluent.platform.all

