- name: set variables
  ansible.builtin.set_fact:
    log_dirs: "{{ broker_log_dirs | default(default_broker_log_dirs) }}"
    log_dirs_prefix: "{{ broker_log_dirs_prefix | default(default_broker_log_dirs_prefix) }}"
    log_filesystem: "{{ broker_log_filesystem | default(default_broker_log_filesystem) }}"

- name: print logs.dir
  ansible.builtin.debug:
    var: log_dirs

- name: print logs.dir prefix
  ansible.builtin.debug:
    var: log_dirs_prefix

- name: print logs filesystem
  ansible.builtin.debug:
    var: log_filesystem

- name: mount disks (Debian/Ubuntu)
  ansible.builtin.include_tasks: ansible_task_mount_disk_debian.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
